[package]
name = "regchest"
version = "0.1.0"
edition = "2021"

[dependencies]
zingo-testutils = { git = "https://github.com/Oscar-Pepper/zingolib.git", version = "0.1.0", branch = "regchest" }
tokio = "1.32.0"

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false

